name: continuse_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg_provider: ^1.0.7
  animated_splash_screen: ^1.3.0
  flutter_product_card: ^0.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/
   
    

flutter_launcher_icons:
  image_path: "assets/applogo.png"
  android: true
  ios: true
  min_sdk_android: 21
dev_dependencies:
  flutter_test:
    sdk: flutter